---
title: "PJI - acelerometro"
author: "Breno, Brenda, Fernanda, Maria Eduarda"
date: "18/08/2024"
output: 
  pdf_document: default
  html_document:
    highlight: tango
    includes:
      after_body: psbfix.html
---

## Bibliotecas

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dygraphs)
library(dplyr)
library(patchwork)
```

# Módulo 1

## Importando arquivos

```{r}
df1_controle <- read.table("Grupo3 Acelerometro Controle.txt", header = TRUE, sep = "\t")

df1_problema <- read.table("Grupo3 Acelerometro Problema Motor.txt", header = TRUE, sep = "\t")
```

## Conversão de dados

```{r}
#Convertendo o separador decimal de ',' para '.'
df1_controle <- as.data.frame(lapply(df1_controle, function(x) as.numeric(gsub(",", ".", x))))

df1_problema <- as.data.frame(lapply(df1_problema, function(x) as.numeric(gsub(",", ".", x))))

#Convertendo DataFrame para classe númerica
df1_controle[] <- lapply(df1_controle, as.numeric)
df1_problema[] <- lapply(df1_problema, as.numeric)
```

## Plotando sinal

```{r}

for (col in names(df1_controle)[-1]) {
  # Criar um gráfico para cada coluna
  dygraph(data.frame(time = df1_controle$Tempo, value = df1_controle[[col]]), main = paste("Gráfico de", col))|>
    dyAxis("x", label = "Tempo (s)") |>
    dyAxis("y", label = "Amplitude") |>
    dyRangeSelector(dateWindow = c()) |> print()  # Para visualizar os gráficos no console do R
}

for (col in names(df1_problema)[-1]) {
  # Criar um gráfico para cada coluna
  dygraph(data.frame(time = df1_problema$Tempo, value = df1_problema[[col]]), main = paste("Gráfico de", col))|>
    dyAxis("x", label = "Tempo (s)") |>
    dyAxis("y", label = "Amplitude") |>
    dyRangeSelector(dateWindow = c()) |> print()  # Para visualizar os gráficos no console do R
}

```

## Observando espectro do sinal

```{r}
fft_signal <- function(time, signal, name){
  dt <- time[2] - time[1] #Resolução temporal
  fs <- 1/dt #Frequência
  rfs <- fs/length(time) #Resolução de frequência
  final_frequency <- (length(time)-1) * rfs #Frequência final
  ff <- seq(from = 0, to = final_frequency, by = rfs) #Vetor de frequência
  signal_fft <- fft(signal) #Transformada de Fourier
  signal_mag <- Mod(signal_fft) #Magnitude do sinal
  signal_theta <- atan2(Im(signal_fft), Re(signal_fft)) #Fase do sinal
  df <- data.frame(ff = ff[1:(length(ff)/2)],mag = signal_mag[1:(length(signal_mag)/2)])
  #, theta = signal_theta[1:(length(signal_theta)/2)]
  
  plot_mag <- dygraph(df, main = paste("Gráfico de", name))|>
    dyAxis("x", label = "Frequência (Hz)") |>
    dyAxis("y", label = "Amplitude") |>
    dyRangeSelector(dateWindow = c(-1,25)) |> print()
  
  #plot_theta <- ggplot2::ggplot(df) + geom_line(aes(x = ff, y = theta), color = "green") + xlab("Frequência (Hz)") + ylab("Fase") + labs(title = paste("Fase do sinal", name))  
  
  
  #plot_all <- plot_mag/plot_theta
  #print(plot_mag)
  return (df)
}

#Amplitude do sinal grupo controle
fft_C1 <- fft_signal(df1_controle$Tempo, df1_controle$C1, "C1 (grupo controle)")
fft_C2 <- fft_signal(df1_controle$Tempo, df1_controle$C2, "C2 (grupo controle)")
fft_C3 <- fft_signal(df1_controle$Tempo, df1_controle$C3, "C3 (grupo controle)")
fft_C4 <- fft_signal(df1_controle$Tempo, df1_controle$C4, "C4 (grupo controle)")
fft_C5 <- fft_signal(df1_controle$Tempo, df1_controle$C5, "C5 (grupo controle)")

#Amplitude do sinal grupo problema motor
fft_DP1 <- fft_signal(df1_problema$Tempo, df1_problema$DP1, "DP1 (grupo problema motor)")
fft_DP2 <- fft_signal(df1_problema$Tempo, df1_problema$DP2, "DP2 (grupo problema motor)")
fft_DP3 <- fft_signal(df1_problema$Tempo, df1_problema$DP3, "DP3 (grupo problema motor)")
fft_DP4 <- fft_signal(df1_problema$Tempo, df1_problema$DP4, "DP4 (grupo problema motor)")
fft_DP5 <- fft_signal(df1_problema$Tempo, df1_problema$DP5, "DP5 (grupo problema motor)")
```

## Cálculo de amplitude MAV - Mean Absolute Value

```{r}
MAV <- function(signal, name){
  MAV_signal <- mean(abs(signal))
  print(paste("Resultado MAV do sinal ", name, ":", round(MAV_signal,3)))
  return (MAV_signal)
}

MAV_C1 <- MAV(df1_controle$C1, "C1 (grupo controle)")
MAV_C2 <- MAV(df1_controle$C2, "C2 (grupo controle)")
MAV_C3 <- MAV(df1_controle$C3, "C3 (grupo controle)")
MAV_C4 <- MAV(df1_controle$C4, "C4 (grupo controle)")
MAV_C5 <- MAV(df1_controle$C5, "C5 (grupo controle)")

print("")

MAV_DP1 <- MAV(df1_problema$DP1, "DP1 (grupo problema motor)")
MAV_DP2 <- MAV(df1_problema$DP2, "DP2 (grupo problema motor)")
MAV_DP3 <- MAV(df1_problema$DP3, "DP3 (grupo problema motor)")
MAV_DP4 <- MAV(df1_problema$DP4, "DP4 (grupo problema motor)")
MAV_DP5 <- MAV(df1_problema$DP5, "DP5 (grupo problema motor)")
```

## Cálculo de frequência - F80

```{r}

F80 <- function(signal_mag,name){
  #Espectro de potência
  power_spectrum <- signal_mag^2
  #Sequência unitária
  ff_unit <- seq(0,1, length.out = length(signal_mag)) * (length(signal_mag)/2)
  #Densidade espectral (PSD)
  psd <- power_spectrum/sum(power_spectrum)
  #Cumulativo da PSD
  cumulative_psd <- cumsum(psd)
  #Identificação da F80
  F80_detected <- ff_unit[which(cumulative_psd >= 0.80)[1]]
  print(paste("Frequência F80 do sinal", name, ":", round(F80_detected,3), "Hz"))
  return(F80_detected)
}

F80_C1 <- F80(fft_C1$mag, "C1 (grupo controle)")
F80_C2 <- F80(fft_C2$mag, "C2 (grupo controle)")
F80_C3 <- F80(fft_C3$mag, "C3 (grupo controle)")
F80_C4 <- F80(fft_C4$mag, "C4 (grupo controle)")
F80_C5 <- F80(fft_C5$mag, "C5 (grupo controle)")
print("")
F80_DP1 <- F80(fft_DP1$mag, "DP1 (grupo controle)")
F80_DP2 <- F80(fft_DP2$mag, "DP2 (grupo controle)")
F80_DP3 <- F80(fft_DP3$mag, "DP3 (grupo controle)")
F80_DP4 <- F80(fft_DP4$mag, "DP4 (grupo controle)")
F80_DP5 <- F80(fft_DP5$mag, "DP5 (grupo controle)")
```

## Cálculo estátisco - Diferença interquartil

```{r}
dif_quartil <- function(signal_mag, name){
  quartil <- quantile(signal_mag)
  inter_quartil <- quartil[4] - quartil[2]
  print(paste("Diferença interquartil do sinal",name,":", round(inter_quartil,3)))
  return(inter_quartil)
}

dif_quartil_C1 <- dif_quartil(df1_controle$C1, "C1 (grupo controle)")
dif_quartil_C2 <- dif_quartil(df1_controle$C2, "C2 (grupo controle)")
dif_quartil_C3 <- dif_quartil(df1_controle$C3, "C3 (grupo controle)")
dif_quartil_C4 <- dif_quartil(df1_controle$C4, "C4 (grupo controle)")
dif_quartil_C5 <- dif_quartil(df1_controle$C5, "C5 (grupo controle)")
print("")
dif_quartil_DP1 <- dif_quartil(df1_problema$DP1, "DP1 (grupo problema motor)")
dif_quartil_DP2 <- dif_quartil(df1_problema$DP2, "DP2 (grupo problema motor)")
dif_quartil_DP3 <- dif_quartil(df1_problema$DP3, "DP3 (grupo problema motor)")
dif_quartil_DP4 <- dif_quartil(df1_problema$DP4, "DP4 (grupo problema motor)")
dif_quartil_DP5 <- dif_quartil(df1_problema$DP5, "DP5 (grupo problema motor)")
```
